name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: asg017/actions/acsweb@master
      with:
        username: asg017
        password: ${{secrets.password}}
        local_dir: ./test
