name: Deploy

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: os-ucsd/actions/acsweb@0.1.0
      with:
        username: asg017
        password: "${{secrets.password}}"
